name: Update Flake Hash on Release

on:
  release:
    types: [published]
  workflow_dispatch:
    inputs:
      version:
        description: 'Version to update (e.g., 0.8.1)'
        required: true

jobs:
  update-hash:
    runs-on: ubuntu-latest
    permissions:
      contents: write
      
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          ref: main
          
      - name: Determine version
        id: version
        run: |
          if [ "${{ github.event_name }}" = "release" ]; then
            VERSION="${{ github.event.release.tag_name }}"
            VERSION="${VERSION#v}"  # Remove 'v' prefix if present
          else
            # Read version from package.json
            VERSION=$(grep '"version"' package.json | cut -d'"' -f4)
          fi
          echo "version=${VERSION}" >> $GITHUB_OUTPUT
          
      - name: Download and calculate SHA256
        id: calculate-hash
        run: |
          VERSION="${{ steps.version.outputs.version }}"
          URL="https://github.com/TibixDev/winboat/releases/download/v${VERSION}/winboat-${VERSION}-x86_64.AppImage"
          
          echo "Downloading from: $URL"
          SHA256=$(curl -sL "$URL" | sha256sum | cut -d' ' -f1)
          
          # Convert to SRI format (sha256-<base64>)
          SHA256_B64=$(python3 -c "import binascii, base64; print(base64.b64encode(binascii.unhexlify('$SHA256')).decode())")
          NIX_SHA256="sha256-${SHA256_B64}"
          
          echo "Calculated SHA256: $SHA256"
          echo "Nix format: $NIX_SHA256"
          echo "nix_sha256=${NIX_SHA256}" >> $GITHUB_OUTPUT
          
      - name: Update flake.nix
        run: |
          NIX_SHA256="${{ steps.calculate-hash.outputs.nix_sha256 }}"
          
          # Update the SHA256 placeholder in flake.nix
          sed -i 's|appImageSha256 = "sha256-[^"]*"|appImageSha256 = "'${NIX_SHA256}'"|' flake.nix
          
          echo "Updated flake.nix with hash: ${NIX_SHA256}"
          
      - name: Commit and push changes
        run: |
          VERSION="${{ steps.version.outputs.version }}"
          
          git config --local user.email "github-actions[bot]@users.noreply.github.com"
          git config --local user.name "github-actions[bot]"
          
          git add flake.nix
          git commit -m "chore: update flake hash for version ${VERSION}" || exit 0
          git push